### ISSUE TITLE
Error Message Misleading

### ISSUE THREAD

**Issue by svetakvsundhar** [terraform-google-modules/terraform-google-data-fusion#14]
When using jsonencode(file()) in the main.tf file of a module, an error saying "Unable to marshal type map(string)" is thrown. However, this issue here is that jsonencode() isn't needed as file() can parse through a JSON file. Is it possible to change the error message to point to the JSON, as the "unable to marshal type.." indicates that is an issue with the Go code?

**Comment by jaketf** [comment]
@svetakvsundhar please re-open this on the [provider itself](https://github.com/GoogleCloudPlatform/terraform-provider-cdap/issues)
