### ISSUE TITLE
Private Network Peering Module needs to be unidirectional

### ISSUE THREAD

**Issue by j-don** [terraform-google-modules/terraform-google-data-fusion#35]
The [peering module](https://github.com/terraform-google-modules/terraform-google-data-fusion/blob/91270dae838823b6014d143fab7cfc2375a9e312/modules/private_network/main.tf#L34) appears to be set up to create peering in both the tenant project and vpc host project. Only the vpc host project should be required, as it seems the tenant project peering gets configured by Data Fusion when the instance is created. Most people running this module won't have access to create this peering in the tenant project anyway.

**Comment by umairidris** [comment]
@jaketf implemented this and might have some insights into why this was there. If it's not needed then we are happy to accept a PR to fix this.

**Comment by jaketf** [comment]
I don't think it's necessary to do both. 
I just chose that implementation because there was existing CFT module for it.
