### ISSUE TITLE
Add capabilities for "DEVELOPER" type instance

### ISSUE THREAD

**Issue by bramanscg** [terraform-google-modules/terraform-google-data-fusion#41]
On the 27th of Jan, Google Cloud Datafusion added a third type instance "DEVELOPER" in addition to their already existing "BASIC" and "ENTERPRISE"

Terraform at the moment caters only to BASIC and ENTERPRISE. Can you add the feature so that we can create DEVELOPER type instances through terraform? 

Google's official Release Notes: https://cloud.google.com/data-fusion/docs/release-notes#January_27_2021

**Comment by umairidris** [comment]
`type` is a string variable so you can set it to any other value.

**Comment by bramanscg** [comment]
This is the error I receive when I do a "terraform plan". I am using the latest terraform release (0.14.6)

% terraform plan

Error: expected type to be one of [BASIC ENTERPRISE], got DEVELOPER

  on ../../modules/scg-udp-etl/datafusion.tf line 31, in resource "google_data_fusion_instance" "datafusion-devel":
  31:   type = "DEVELOPER"

**Comment by umairidris** [comment]
Try sending a PR to add the value to https://github.com/GoogleCloudPlatform/magic-modules/blob/ddbe342494d6dc9bee6b6718c3710176ba10a3f5/mmv1/products/datafusion/api.yaml#L88.

**Comment by bramanscg** [comment]
Thanks submitted. https://github.com/GoogleCloudPlatform/magic-modules/pull/4494

**Comment by umairidris** [comment]
Happy to help!
