### ISSUE TITLE
Dataproc Service account argument is not available in terraform but available in console

### ISSUE THREAD

**Issue by msbhati08** [terraform-google-modules/terraform-google-data-fusion#42]
Hi Team,

When creating data fusion instance through cloud console I am getting option to use Dataproc service account but in terraform not having that argument itself.

**Comment by rileykarson** [comment]
You'll want to file an issue against the provider at https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=&template=enhancement.md in addition to here
