### ISSUE TITLE
Enable Replication module ? 

### ISSUE THREAD

**Issue by Guimove** [terraform-google-modules/terraform-google-data-fusion#45]
Hello,

Is there a way to enable the replication accelerator?

I’ve not seen any occurrence of this neither on the ’google_data_fusion_instance` resource nor in this module.

Do you have any hints? 

Actually, I’m using a custom null_resource to run after the instance creation : 

```
curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
-H "Content-Type: application/json" \
${CDAP_ENDPOINT}  -X PATCH -d '{ "accelerators":[{"accelerator_type":"CDC", "state":"ENABLED"}]}'
```

But this is not really flexible.

**Comment by fmaach** [comment]
This resource is critical. Please deliver it for your Google Datafusion customers.

**Comment by FVCCarneiro** [comment]
I have this same doubt / issue. It would be important to be able to add this directly on the "google_data_fusion_instance" resource!

**Comment by remydavid** [comment]
+1

**Comment by suchitgupta01** [comment]
Is there a way to achieve it via terraform?

**Comment by suchitgupta01** [comment]
@Guimove Is there a way to get it done via Terraform?

**Comment by ptran32** [comment]
@suchitgupta01 there is an open issue for Terraform support: https://github.com/hashicorp/terraform-provider-google/issues/9070
