### ISSUE TITLE
No use of data_fusion_instance resource?

### ISSUE THREAD

**Issue by jaketf** [terraform-google-modules/terraform-google-data-fusion#6]
@morgante 
It appears the [`main.tf`](https://github.com/terraform-google-modules/terraform-google-data-fusion/blob/master/main.tf) of this root module contains only a GCS bucket (no use of [`data_fusion_instance`](https://www.terraform.io/docs/providers/google/r/data_fusion_instance.html)).

Is this repo just a placeholder?

**Comment by morgante** [comment]
@umairidris It looks like this module only includes a submodule. We can probably remove the root module if that's the desired behavior.

**Comment by umairidris** [comment]
The root module should be dedicated to the data fusion instance. I followed up with the original owner of this and they don't have much bandwidth, so I can take it on and add a basic instance as the root module to get us started.

**Comment by morgante** [comment]
Sounds good, thanks!
