### ISSUE TITLE
Add submodules to simplify setup of network and dataproc stack

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-google-data-fusion#8]
We should add a couple of submodules that can simplify setting up the network and dataproc stacks:

- created ip allocation for peering
- created the peering
- Created SSH ingress FW rule source: P4 SA target dataproc subnet
- A place to add SA permissions to add to the data fusion P4 SA

**Comment by jaketf** [comment]
this should be closed as of #10.
however note that #30 is additionally needed for use with VPC-SC
